### ISSUE TITLE
Markdown type card

### ISSUE THREAD

**Issue by damianeickhoff** [mrpharderwijk/hass-nolu#4]
Seems like there is an issue with the markdown type card. If you define a Markdown card underneath the widgets and give it some content, It always return "just a markdown"

for example:
```
home:
  title: 'Home'
  icon: 'mdi:home-assistant'
  url: 'home'
  show_in_navbar: true
  show_header: true
  rows:
    - widgets:
        - type: default_weather
          entity: weather.thuis
        - type: markdown
          content: |
            hello, {{user}}
```

results in this:
![image](https://user-images.githubusercontent.com/12126826/128866144-74636b09-7e4e-409e-a733-672293ad49ed.png)
